ndorname: Build Armbian Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm # ubuntu-24.04-arm, ubuntu-24.04-riscv
    steps:
      - uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: "rock64" # orangepi5 bananapif3
          armbian_release: "trixie" # trixie
          armbian_target: "build"
          armbian_kernel_branch: "current"
          armbian_ui: "server" # server xfce
          armbian_runner_clean: "yes" # recommended for Github runners
